# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: distributed_ai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'distributed_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64istributed_ai.proto\"$\n\x0ePredictRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\"%\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\"R\n\x0f\x43ritiqueRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x1b\n\x13previous_prediction\x18\x02 \x01(\t\x12\x11\n\trationale\x18\x03 \x01(\t\"$\n\x10\x43ritiqueResponse\x12\x10\n\x08\x63ritique\x18\x01 \x01(\t2l\n\x0bNodeService\x12,\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse\x12/\n\x08\x43ritique\x12\x10.CritiqueRequest\x1a\x11.CritiqueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distributed_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=24
  _globals['_PREDICTREQUEST']._serialized_end=60
  _globals['_PREDICTRESPONSE']._serialized_start=62
  _globals['_PREDICTRESPONSE']._serialized_end=99
  _globals['_CRITIQUEREQUEST']._serialized_start=101
  _globals['_CRITIQUEREQUEST']._serialized_end=183
  _globals['_CRITIQUERESPONSE']._serialized_start=185
  _globals['_CRITIQUERESPONSE']._serialized_end=221
  _globals['_NODESERVICE']._serialized_start=223
  _globals['_NODESERVICE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
